### ISSUE TITLE
Can not resolve the library

### ISSUE THREAD

**Issue by ozbek** [batoulapps/adhan-kotlin#1]
Added `compile 'com.batoulapps.adhan:adhan:1.0.0'` as mentioned in the readme, but gradle is failing with "_Failed to resolve: com.batoulapps.adhan:adhan:1.0.0_" message. I tried with

```
maven {
    url "https://repo.maven.apache.org/maven2"
}
```

Where the artifacts are published?

**Comment by ahmedre** [comment]
it's here - not sure why it's not working at the moment 😐  https://bintray.com/batoulapps/adhan/com.batoulapps.adhan/1.0.0

**Comment by ozbek** [comment]
JazakAllah khair, it worked with the following: 

```
maven {
    url  "https://dl.bintray.com/batoulapps/adhan"
}
```
