### ISSUE TITLE
Is sunnahtime fix present in version 1.1.0

### ISSUE THREAD

**Issue by msadrud** [batoulapps/adhan-kotlin#10]
Hi,
I recently noticed that the library is updated with sunnah time. Thanks a lot for this useful feature.
However, I didn't see any update on the version. The version is still 1.1.0.
Are you planning to release a new version with this new feature in [https://bintray.com/batoulapps/adhan/com.batoulapps.adhan](url) ?

Also, it would be great if the usage documentation is updated with the latest feature.

Thanks a lot for your great work.

**Comment by ahmedre** [comment]
yep, that's right - in sha' Allah will release a new version.

**Comment by ghost** [comment]
Do we have Sunnah time implemented in Java? This is quite nice one. Please add if it is not in Java already.

**Comment by ahmedre** [comment]
yes, i think `SunnahTimes` have been there for a while - will look into updating over the weekend in sha' Allah since i thought i did at some point but might not have updated the docs afterwards.

**Comment by ghost** [comment]
Thanks a lot. Looking forward to get SunnahTimes in java library.

**Comment by ahmedre** [comment]
published 1.2.0 - closed by #11
