### ISSUE TITLE
Query on offset for Zuhr and Maghrib prayers

### ISSUE THREAD

**Issue by tanweermaniyar** [batoulapps/adhan-kotlin#17]
Excellent work. I am aiming to deduce mid-day(zenith) and sunset(time) from your output. In other words- how many minutes shall I deduct from zuhr start-time, and how many from maghrib start-time as calculated by your library.

Many thanks in advance.

**Comment by z3bi** [comment]
Most of the calculation methods add a minute for Dhuhr and  some methods add a few minutes to Maghrib. However if you use the `OTHER` calculation method (give it something reasonable like 18 degrees for fajr and isha) then the value for zenith will be the dhuhr time and the value for maghrib will be sunset exactly.

You can get a sense of what each method does by looking at https://github.com/batoulapps/adhan-java/blob/master/adhan/src/main/java/com/batoulapps/adhan/CalculationMethod.java

**Comment by tanweermaniyar** [comment]
OK thanks. I have a separate question. How do you calculate the end time for Asr prayer please? Is that relative to sunset i.e. start time of Asr as calculated by Hanafi or other methods- and end time being the sunset time? or we deduct a few minutes from the sunset time- could you please extend your valuable advice?

**Comment by z3bi** [comment]
@tanweermaniyar If you are interested in showing the end of Asr time (as in not just showing the start of Maghrib) my recommendation would be to take a safe offset from Maghrib. A value of 10 minutes would be sufficient to cover any additional time that some of the methods use and have a nice buffer from sunset. For the end of a prayer its better to keep a few extra minutes as a buffer, especially when looking at something like apparent sunset which can affected be various environmental factors.

**Comment by tanweermaniyar** [comment]
Thank you. Really appreciate.
