### ISSUE TITLE
Query on fajr start time with 18 deg angle and Magrib time

### ISSUE THREAD

**Issue by tanweermaniyar** [batoulapps/adhan-kotlin#18]
Is there an offset of -3 minutes to true twilight start with 18 deg methods. I am getting for my location a time, which is 3 minutes less than reported in the link here-
My Lat : Long - 52.0620° N, 1.2705° E

https://www.thetimeandplace.info/uk/martlesham-heath-suffolk#.Xy_WMYhKjIU

Second question I have is, what should be end time for Maghrib- is it until twilight totally disappears- and exactly when Isha starts? (I am aware of Ahadith where it's preferred to pray in the beginning of time- but just checking what's your view?)

**Comment by z3bi** [comment]
If you're using the Moonsighting Committee Method, that method specifies a 3 minute buffer after the start of sunset for the sun to be fully set before it is considered time for Maghrib.

In terms of the FINAL end time for Maghrib, my understanding is that would be up until it is time for Isha.
