### ISSUE TITLE
Thanks -managed to publish my app

### ISSUE THREAD

**Issue by tanweermaniyar** [batoulapps/adhan-kotlin#22]
I wasn't sure where to comment so writing in Issues though it's not one.

Would like to thank the publisher of this useful library. What started as a personal project, I managed to publish Salat times app for Android recently. The feedback is generally positive. New to GitHub so not sure if one is allowed to share install links here.
Strongly recommended library and it was a breeze to integrate. 
Thank you very much.

Edit(13/11)
https://play.google.com/store/apps/details?id=com.amsalat.almisbhasalattimes

**Comment by tanweermaniyar** [comment]
So here sharing Android app link to demo the use of this beautiful java library. Please note this is a totally free app and only reason of sharing is to show implementation example. 

https://play.google.com/store/apps/details?id=com.amsalat.almisbhasalattimes

**Comment by ahmedre** [comment]
masha'Allah, jazakumAllah khairan for sharing!
