### ISSUE TITLE
Failed to resolve: com.batoulapps.adhan:adhan:1.2.0

### ISSUE THREAD

**Issue by hamza94max** [batoulapps/adhan-kotlin#24]

**Comment by ahmedre** [comment]
please make sure to add:

```
maven {
   url "https://dl.bintray.com/batoulapps/adhan"
}
```

to your build.gradle.

**Comment by hamza94max** [comment]
Already added , the error is the second is ( compile 'com.batoulapps.adhan:adhan:1.2.0')

@ahmedre

**Comment by ahmedre** [comment]
it's working for me - please try with this sample project.

[prayertimes.zip](https://github.com/batoulapps/adhan-java/files/5683589/prayertimes.zip)

**Comment by hamza94max** [comment]
Thanks alot 
@ahmedre
