### ISSUE TITLE
Qibla Function

### ISSUE THREAD

**Issue by herwin20** [batoulapps/adhan-kotlin#36]
How to Use Qibla Function to result angle ??

**Comment by GulmirzaNorboyev** [comment]
> How to Use Qibla Function to result angle ??

Assalamu alaykum! I used the Qibla direction function to calculate the angle relative to the north on the compass, and the result is excellent! I have a compass app and it rotates according to the sensor, I add the angle towards the qibla to that angle of rotation, as a result, the direction of the qibla also takes the direction corresponding to the north...

<img width="1033" alt="Снимок экрана 2021-09-19 в 01 49 23" src="https://user-images.githubusercontent.com/47708807/133908191-da69fed5-3d86-4ca6-bb6b-08856ce5545b.png">

<img width="832" alt="Снимок экрана 2021-09-19 в 01 50 22" src="https://user-images.githubusercontent.com/47708807/133908193-16822398-cfee-40f7-a6ed-06480fb9e3ac.png">

![Screenshot_1631998104](https://user-images.githubusercontent.com/47708807/133908256-7365c66c-fbc3-4baf-a894-c776f5ffd9fa.png)

**Comment by herwin20** [comment]
Walaikum salam brother ..
Thanks for reply it .  I will try it
