### ISSUE TITLE
java and swift have time difference on the same location

### ISSUE THREAD

**Issue by Bilalwarind** [batoulapps/adhan-kotlin#38]
while using library for both swift and java getting 3 to 10 minutes difference on android and ios devices on the same location.
like while testing it in London ===> Prayer times on android and ios
Andriod fajr 4.58. ios 5.01

Dhuhr andriod 12.16 ios 12.12

Asr andriod 03.13. Ios 03.13

Maghrib  andriod 05.56 ios 05.53

Isha'a Andriod 07.13  IOS 07.24

**Comment by walida890** [comment]
This is for the moonsighting method.

**Comment by z3bi** [comment]
@walida890 the most likely issue is a difference in how the calculation parameters are being setup. Can you post your java code and your swift code for how you're creating the CalculationParameters, coordinates, and your call to create the prayer times.

**Comment by Bilalwarind** [comment]
> 
![WhatsApp Image 2022-03-15 at 9 53 29 PM](https://user-images.githubusercontent.com/23113647/158519516-ffc3650c-5022-4e79-bdef-e0459d1270da.jpeg)
![WhatsApp Image 2022-03-15 at 9 53 31 PM](https://user-images.githubusercontent.com/23113647/158519535-7c95ba1b-fc4f-4c10-ad5f-23f93a9747da.jpeg)

> here it is swift

**Comment by Bilalwarind** [comment]
![java](https://user-images.githubusercontent.com/23113647/158519874-82593758-9bc3-4bf3-bff0-6083f243c9c1.jpg)
![java2](https://user-images.githubusercontent.com/23113647/158519889-16c39d4c-7e2e-4858-9591-b5cfebc5adc2.jpg)

> here it is java

**Comment by ahmedre** [comment]
It looks like the calculation method is different between your Swift example and your Java example. May you double check it?

**Comment by ahmedre** [comment]
closing for now, please reopen if this is still an issue.
