### ISSUE TITLE
Extract the Kotlin Mutliplatform version to a seperate repository

### ISSUE THREAD

**Issue by skaldebane** [batoulapps/adhan-kotlin#42]
Asslamu Alaikum! I just came across this library through one @ahmedre's talks, yet had a hard time finding it here (there's nothing about it in the main Adhan repo), because it's a branch in this repo.

I guess it would be better if it was separated into its own library, simply called adhan-kotlin (many people may just want to use the Kotlin version on Android without caring for KMP, so this name would make more sense for them).

Thanks!

**Comment by skaldebane** [comment]
Any updates on this?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
no update - still not sure whether we'll do this or keep them as part of the same repo. @z3bi / @sgtsquiggs any strong opinions here? I don't mind maintaining both versions but there's little reason to keep maintaining a Java version if a Kotlin version exists (considering it also compiles down to the JVM).

if we keep it in the same repo, we could switch to having the main branch be the kmp branch, which would then have a link to the old branch.
walsalam 3alaikum

**Comment by sgtsquiggs** [comment]
I would say take the option with the least ongoing maintenance. We can update documentation to make it easier to find if that is a problem.

**Comment by skaldebane** [comment]
I agree with @ahmedre, maintaining both the Java and Kotlin libraries is generally repeated work since the Kotlin version can work perfectly with Java (on the JVM).
I think it's a good way forward as it will reduce the maintenance cost of having to keep two versions of the same thing in sync.

**Comment by GulmirzaNorboyev** [comment]
Assalomu alaykum! I think it's better to use the `Kotlin DateTime API`, not `java.util.Calendar`, for the library to work properly for **KMM**, to work on both platforms...

**Comment by ahmedre** [comment]
wa3laikum alsalam -
we are in the `kotlin_multiplatform` branch since otherwise it wouldn't work with Kotlin Multiplatform.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
salam 3alaikum,
we've made the KMP version the primary one since the KMP version works on Java targets.
we won't be splitting the repositories at this time.
walsalam 3alaikum.

**Comment by skaldebane** [comment]
Jazakallah brother, that's the best way forward.

**Comment by ahmedre** [comment]
waiyyakum!
