### ISSUE TITLE
Next Prayer Time (nextPrayer())

### ISSUE THREAD

**Issue by abdulbasid123** [batoulapps/adhan-kotlin#49]
How can I set nextPrayer() method in java version of this (blessed) library ?

I tried the same way that the normal sequence of prayer times are set like this 👉  binding.nextPrayerTime.setText(" "+ format.format(nextPray.nextPrayer());

But the app crashes at start up.

**Comment by ahmedre** [comment]
may you send the example of code you are using and the exception / crash you're seeing?

**Comment by ahmedre** [comment]
closing, please re-open if you still have an issue with this.
