### ISSUE TITLE
Milliseconds difference for the same prayer

### ISSUE THREAD

**Issue by alaa-moataz** [batoulapps/adhan-kotlin#50]
Hello,

Thank you for implementing this library it's really helpful, 
I noticed one issue is that the milliseconds part of any returned date for prayers can differ given the same Coordinates , Date & CalculationParameters

The code below outputs "Max is 1681351380999 and min is 1681351380000"
<img width="502" alt="image" src="https://user-images.githubusercontent.com/59055914/231742760-298e3776-5a26-40e2-b3e3-98da1c069d33.png">

I think in your `TimeComponents.java` in `dateComponents` function you should add `calendar.set(Calendar.MILLISECOND, 0)`

**Comment by sgtsquiggs** [comment]
Thanks for finding this issue - we'll get around to fixing this ourselves but sooner if you would create a PR for this change (with an additional unit test)! We'd appreciate it!

**Comment by ahmedre** [comment]
Nice find! Will fix this for both the Java and Kotlin versions probably this weekend (unless @sgtsquiggs gets to it first).

**Comment by alaa-moataz** [comment]
@sgtsquiggs @ahmedre I can create a PR for it today

**Comment by ahmedre** [comment]
JazakumAllah khairan
