### ISSUE TITLE
Which madhab (Hanafi / Safi for Asr calculation) to use with a particular calculation method

### ISSUE THREAD

**Issue by skkshoaib** [batoulapps/adhan-kotlin#58]
Salaam

I am quite confused about which asr calculation madhab to use.

I see that CalculationMethod (MUSLIM_WORLD_LEAGUE,UMM_AL_QURA...) doesn't by default include madhab but rather all of them default to sahfi. Does it mean that the calculation method and madhab have no association?

Similarly for HighLatitudeRule. Is there no association between the Calculation Method and HighLatitudeRule?

I asked here too https://github.com/batoulapps/Adhan/issues/105 however I see that this repo has more activity so posting here too. 

JazakAllah khairun

**Comment by z3bi** [comment]
See my response here https://github.com/batoulapps/Adhan/issues/105#issuecomment-1799094949
