### ISSUE TITLE
Sunnah Times

### ISSUE THREAD

**Issue by BassamxMednini** [batoulapps/adhan-kotlin#8]
As salaamu aleykum,

is there no way to calculate the Sunnah times like in the [swift library](https://github.com/batoulapps/adhan-swift#sunnah-times)?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
not yet, but i'll implement this soon in sha' Allah.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
this is implemented in #9
